### ISSUE TITLE
document when arguments would be null

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-motion#121]
Related to code review #103.

In ProjectileObjectType, 3 constructor parameters are documented as having `null` as a possible value:

```js
@param {string || null} name - name of the object, such as 'Golf ball'
...
@param {string || null} type - identifier of the object type, such as 'tankShell'
@param {boolean || null} rotates - whether the object rotates or just translates in air
```

In general, you should document why/when something would be `null`.

**Comment by pixelzoom** [comment]
It seems especially odd (and potentially dangerous) that `rotates` would have `null` as a possible value, since `false` and `null` both are falsey.

**Comment by pixelzoom** [comment]
These assignments also seem strange;

```js
43    this.name = name || null;
      ...
47    this.type = type || null;
48    this.rotates = rotates || false;
```

If `null` is indeed a valid argument, then lines 43 and 47 should be unnecessary. 

Line 48 is basically saying if the `rotates` argument is not truthy, then set `this.rotates` to false.

**Comment by jbphet** [comment]
I'm looking at some of the review items since @pixelzoom is going on vacation soon and I need to be up to speed to field any questions.  It looks like support for null values in the constructor is used mostly for constructing the projectile object types for `VECTORS_SCREEN` and `DRAG_SCREEN`.  It strikes me odd that these are projectile object types at all.  How is, say, `VECTORS_SCREEN` the same sort of thing as `GOLF_BALL`?  This makes me suspect that there is some inappropriate reuse of this type that should be broken out into a separate type.

**Comment by pixelzoom** [comment]
👍 Closing.
