### ISSUE TITLE
Gamify the target by adding a bit of scoring!

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#126]
@andrea-phet @arouinfar if it isn't too much work, it would be sweet to vary the amount of stars "received" when hitting the target. This would depend on where the projectile lands. So, hitting the outer red ring would only have ONE star float up, hitting the white ring would be two stars, and hitting a bullseye would be all three stars.

![screen shot 2017-07-26 at 12 55 28 pm](https://user-images.githubusercontent.com/5863899/28638623-9fab46de-7202-11e7-906b-d24f5ef0109f.png)

![screen shot 2017-07-26 at 1 03 37 pm 2](https://user-images.githubusercontent.com/5863899/28638994-d79acdde-7203-11e7-8def-32d69dcbad3e.png)

![screen shot 2017-07-26 at 1 05 29 pm 2](https://user-images.githubusercontent.com/5863899/28639210-a5bf40d2-7204-11e7-846f-53592a13802f.png)

![screen shot 2017-07-26 at 1 09 41 pm 2](https://user-images.githubusercontent.com/5863899/28638993-d79624a0-7203-11e7-8015-0423589fc84a.png)

**Comment by arouinfar** [comment]
@phet-steele I really like this suggestion!  I've thought that it's a little odd to give the same feedback for landing anywhere within the ~3m range of the target. 

During interviews, one student made a comment about getting all three stars because he hit the bullseye (the other 4 made no such remarks), so it's possible that *some* students may connect the number of stars to their accuracy. This expectation isn't unreasonable, as the target is an implicit "game" and mobile games generally award 1-3 stars when completing a level.

If this is a feasible change, I would like to pursue it @andrea-phet. Let's discuss when you return.

**Comment by andrea-phet** [comment]
Yes, very feasible. @arouinfar and @phet-steele how does it look?

**Comment by arouinfar** [comment]
Love it! Thanks @andrea-phet.

**Comment by ariel-phet** [comment]
This change turned out very nicely btw. Tried it when showing the sim to a 4 year old, and asked him to make changes to try to get 3 stars.
