### ISSUE TITLE
Legends of Learning Icons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/projectile-motion#150]
Need to create icons for Legends of Learning.

**Comment by arouinfar** [comment]
@kathy-phet @samreid here's a rough draft of the icons, inspired by the screen icons. I'll be working on these icons more tomorrow, and welcome any feedback.

![lol-icon-pm-01](https://user-images.githubusercontent.com/8419308/29848151-27789816-8cdc-11e7-835c-5ef7cd6fb993.png)
![lol-icon-pm-03](https://user-images.githubusercontent.com/8419308/29848153-277a4292-8cdc-11e7-9f07-e35a1a1ad8e6.png)
![lol-icon-pm-02](https://user-images.githubusercontent.com/8419308/29848154-277d2cdc-8cdc-11e7-91e0-9e0563058574.png)
![lol-icon-pm-04](https://user-images.githubusercontent.com/8419308/29848152-27799356-8cdc-11e7-98ec-e1b3dee2b3c7.png)

**Comment by samreid** [comment]
This kind of overlapping seems awkward:
![image](https://user-images.githubusercontent.com/679486/29849545-bfd1bc20-8ce4-11e7-8fe9-21907e228023.png)

This seems awkward too (how drag is in the street):
![image](https://user-images.githubusercontent.com/679486/29849563-e541daf8-8ce4-11e7-8961-1badcd66ee82.png)

Not sure of the best solution though.

**Comment by arouinfar** [comment]
Thanks for the feedback @samreid! 

For Intro, I played with the placement a bit to try and make the overlap the less invasive, but maybe I should instead alter the path so it's not coming from the lower corner.

For Drag, I'll try a version with the projectiles in the air. "Drag" does look a bit odd trapped in the road.

**Comment by samreid** [comment]
Having the motion be "up and to the right" seems great--what about moving the text?

**Comment by arouinfar** [comment]
> Having the motion be "up and to the right" seems great--what about moving the text?

@samreid for consistency, we should stick with the template, which has the text in the lower left.

I was able to tweak the icons so that there's minimal/no overlap with the text.

![lol-icon-pm_intro](https://user-images.githubusercontent.com/8419308/30139750-fe5e7dfe-932c-11e7-8249-018d07947ec0.png)
![lol-icon-pm_vectors](https://user-images.githubusercontent.com/8419308/30139752-fe652032-932c-11e7-914a-303439a26f54.png)
![lol-icon-pm_drag](https://user-images.githubusercontent.com/8419308/30139749-fe5e5716-932c-11e7-9293-5a3850c1c221.png)
![lol-icon-pm_lab](https://user-images.githubusercontent.com/8419308/30139751-fe62b3a6-932c-11e7-9fdc-63a7ed10bfce.png)

**Comment by kathy-phet** [comment]
I like these! Thanks.

**Comment by arouinfar** [comment]
Thanks @kathy-phet!

@samreid responded in Slack:
> Looks great!

@samreid I've added the .ai asset and .png files to the [Drive folder](https://drive.google.com/drive/u/0/folders/0BwZJWzOg9l4DOFhPRzlKYWVfY3c). Feel free to close after you review.

**Comment by samreid** [comment]
I can see them in the drive folder and they look good.  For next steps: @kathy-phet said she would request a designer to submit the sims/icons/metadata to LOL.  I think this issue can be closed.
