### ISSUE TITLE
User request: remove gravity

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#154]
> Can't reduce gravity. I want to demonstrate to my students what happens when you reduce whole gravity force (demonstrate Newton's 1 law) but it's impossible on this simulation. Can you fix this?
> 
> I know that I can reduce the gravity down to 5.0 m/s^2, but can I reduce it down to 0 m/s^2?

**Comment by arouinfar** [comment]
My initial reaction to this request was that it's beyond the scope of the sim, but I decided to think about possible learning goals for g=0 and what design changes would be necessary. There are two cases to consider for g=0: no air resistance vs. air resistance.

(1) Without air resistance, one goal of g=0 could be to show that the projectile travels in a straight line at a constant velocity. The Motion screen of FAMB already addresses this goal, albeit in a different context and in 1D only.

(2) With air resistance, one possible goal would be to explore situations similar to this:
![screen shot 2017-10-02 at 5 20 11 pm](https://user-images.githubusercontent.com/8419308/31103760-fe1c8854-a795-11e7-8220-ff79bd470105.png)

Allowing g=0 would also come with some challenges.
* Because y would never be zero, there would probably need to be some flag for "finished" projectiles. (Only 5 trajectories and 3 active projectiles are allowed at once.)
* Trajectories with many dots can bog down the performance. 
* For case (1), the trajectory should terminate at (or slightly beyond) the dev border of the most zoomed out state.
* For case (2), the velocity asymptotically approaches zero, which could be programmatically challenging. There would likely need special to be case code (if g=0, create a floor value so that velocities below a the threshold are set to zero) to avoid an infinite number of dots being drawn, and so that the "finished" flag can flip to 'true'.

Given these complexities, I'm not too keen on allowing g=0, but perhaps we should discuss it in light of the other pending design changes. Thoughts @ariel-phet?

**Comment by ariel-phet** [comment]
I think given that sim is called "projectile" motion, a projectile involves gravity. All the learning goals in my mind are centered around the idea that vector components need to be used to understand/calculate the motion.

So I am not keen on this idea either. 

@oliver-phet can you refer the user to FAMB, which has 1d motion and Newton's Law well covered? That sim is much more appropriate for the learning goals.

**Comment by oliver-phet** [comment]
Email to user sent. Closing for now.
