### ISSUE TITLE
User issue: David

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/projectile-motion#158]
> I recently found your simulations and I am very excited to use them! What a great resource. Specifically, right now, I want to use projectile motion but I can not because of the David statue. David is covered by a leaf but a fourth grade class will not be able to get passed that. Is there any way that you can remove David or cloth him more? It would be a shame to not use this simulation because it is perfect otherwise. I am sure that other teachers will share in my concern.
<img width="164" alt="screen shot 2017-10-09 at 9 50 39 pm" src="https://user-images.githubusercontent.com/5090275/31399522-d81e9fb0-ada9-11e7-9530-69c38b8d61be.png">

**Comment by ariel-phet** [comment]
An easy fix would just be to keep his shorts on, I think @arouinfar and I are both fine with this.

@pixelzoom would removing the "easter egg" of shooting David's shorts off be difficult/time consuming (I am assuming that would be easy). No need to take any action, just curious.

**Comment by amanda-phet** [comment]
Do you really think this is a concern worth spending time on? This is not a new feature to the HTML5 sim so I'm curious how many teachers have emailed phethelp about this being an issue in the past.

**Comment by oliver-phet** [comment]
No other emails have been received about this.

**Comment by pixelzoom** [comment]
So many things I'd like to say here, but won't.

@jbphet is listed as the responsible developer for this sim.  That said..

Easy to disable this Easter egg - remove `ProjectileMotionModel.davidShortsOnProperty` and all occurrences of it.  But just disabling introduces some "code hygiene" problems. If you're actually going to make this change, then I recommend changing the artwork, so that we don't have separate "pants on" and "pants off" images. So combine david_bottom.png and david_middle.png into 1 image (looks like david.ai is already set up for this), delete david_shorts.png, update images/license.json.

**Comment by pixelzoom** [comment]
This change would take me < 30 minutes, followed by a 2-hour bicycle ride to calm down.

**Comment by ariel-phet** [comment]
@amanda-phet - yes, I do. If someone is motivated enough to email us, we need to consider it. We made a similar change to pH Scale when a teacher said they could not use it because we included beer. I am not at all tied to this easter egg. It is cute and all, but it has no value otherwise. David having on shorts is kind of whimsical to begin with.

**Comment by jbphet** [comment]
I suppose as the responsible dev I should chime in.  I'm too am okay with disabling the Easter egg, and I'll just go on the ride with @pixelzoom.  Assign to whomever you'd like to do it if it is decided to go ahead and take it out.

**Comment by arouinfar** [comment]
As sims are ported to HTML5 they may end up with more use at the younger grade levels than the original Java/Flash, in part due to the technology in the classroom, and in part due to purposeful scaffolding to target younger learners. 

Personally, I'm a fan of the David easter egg and find the request to be a bit puritanical. That said, David's shorts do not serve any real learning goal, and there is still plenty of whimsy elsewhere in the sim. If keeping David's shorts on will open the sim up to broader use, then I'm all for it.

**Comment by arouinfar** [comment]
@ariel-phet can you reassign to the appropriate dev? I'll also update the David asset as @pixelzoom described.

**Comment by ariel-phet** [comment]
@arouinfar agreed on the puritanical bit, but also on the understanding of opening up to a broader audience.

@jbphet we will have you take care of this since it is a pretty quick change. No huge rush.

@oliver-phet please email the user and let them know we will be modifying the sim.

**Comment by oliver-phet** [comment]
User emailed.

**Comment by arouinfar** [comment]
Self-assigning to update the artwork.

**Comment by pixelzoom** [comment]
@arouinfar There are no updates needed to david.ai.   Updates to PNG files are described above:
> So combine david_bottom.png and david_middle.png into 1 image (looks like david.ai is already set up for this), delete david_shorts.png, update images/license.json.

**Comment by arouinfar** [comment]
@pixelzoom my plan was to re-export David as single image, and also remove David's extra layers from the .ai file. 

Only the left-most artwork in the .ai file is relevant now. 
![image](https://user-images.githubusercontent.com/8419308/32118411-dadcad42-bb0e-11e7-8695-30d1809d3203.png)

**Comment by pixelzoom** [comment]
@arouinfar If the arm no longer needs to move separately, then that sounds like a fine plan - reduce David to a since file: david.ai and david.png.

**Comment by pixelzoom** [comment]
@ariel-phet @jbphet Since I've already had my nose in this a fair amount, I don't mind taking care of it, if @jbphet doesn't mind.

**Comment by pixelzoom** [comment]
@ariel-phet @jbphet Since I've already had my nose in this a fair amount, I don't mind taking care of it, if @jbphet doesn't mind. (And I could use the bike ride :)

**Comment by pixelzoom** [comment]
Origins of the David fig leaf: http://www.vam.ac.uk/content/articles/d/davids-fig-leaf/.  Good to see that our attitudes about nudity have matured so much since 1857 (not).

**Comment by arouinfar** [comment]
The David asset has been updated and emailed.

**Comment by pixelzoom** [comment]
There's another issue that I'm going to fix while I'm in here. `ProjectileMotionModel` defines `davidPosition {Vector2}`, but it's never used.  Instead the view gets constants from `ProjectileMotionConstants`.  I'm going to make the view get David's height and position from the model, as was apparently intended.

**Comment by pixelzoom** [comment]
@arouinfar please verify in [1.1.0-dev.1](https://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.1.0-dev.1/projectile-motion_en.html).  Compare to published version [1.0.1](https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_en.html), check that nothing happens when David is hit, and that zoom works as expected.   If everything looks OK, I'll proceed with a maintenance release.

**Comment by pixelzoom** [comment]
Note to self: Changes still need to be cherry picked to 1.0 release branch. See https://github.com/phetsims/projectile-motion/commit/1d292827afe6f49718b68d171a556cd13d1cbca3.

**Comment by arouinfar** [comment]
Everything looks good @pixelzoom. David's lower half remains clothed, and I haven't encountered any zooming artifacts.

**Comment by pixelzoom** [comment]
Zoom call with @jbphet:  Instead of doing a separate maintenance release for this issue, @jbphet would like to do 1 maintenance release for #155, #158 (this issue) and #159.  So I'll make the changes in the 1.0 release branch, then assign this issue to him to complete the maintenance release.

**Comment by pixelzoom** [comment]
Changes to 1.0 branch in the above commit.  I tested both the requirejs and built versions (to verify that license.json was OK).  FYI, David's formerly dropped his drawers with cannon=80°, initial speed=13m/s.  Over to @jbphet for maintenance release.

**Comment by jbphet** [comment]
The fix for this is available in https://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.2-rc.1/projectile-motion_en.html.

**Comment by phet-steele** [comment]
Fixed 😞 . Will notify @oliver-phet when ready.

**Comment by jbphet** [comment]
The "stickier pants" change was included in the 1.0.2 release, which is now live on the main site.  @oliver-phet - please notify the person or people who requested this change and close the issue.

**Comment by oliver-phet** [comment]
Email to user sent. Closing.
