### ISSUE TITLE
When compiling I get Fatal error: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ayrimsal** [phetsims/projectile-motion#162]
When I run:
npm install
grunt --brand=mybrand --locales=tr
I get 
Running "after-requirejs-build" task
Fatal error: Cannot read property 'trim' of undefined
Is there a solution to this?

**Comment by jbphet** [comment]
This issue is over a year old and isn't assigned to anyone.  I'm revisiting the list of open issues in preparation for some work being done, so I'll try to answer the developer's question.

@ayrimsal - The only use of `.trim` that I see anywhere in the code is `StringUtils.trim()`, so my best guess is that you don't have the latest version of that dependency.  If you're working off of master, please try running the script `pull-all.sh` that resides in the `<your-root>/perennial/bin` directory.

**Comment by zepumph** [comment]
We haven't heard from you in a while @ayrimsal! I hope this problem was fixed. I'm going to close this issue but please feel free to reach out again if you run into trouble.
