### ISSUE TITLE
PhetIO Studio wrapper Drag Coefficient crash

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/projectile-motion#214]
<b>Test Device</b>

Windows 7 Laptop

<b>Operating System</b>

Windows 7

<b>Browser</b>

Chrome

<b>Problem Description</b>
Tested on request for Michael Kauzmann
In phet.io studio
If projectileDragCoefficientProperty is set to 0 then a projectile is emitted, sim crashes

<b>Steps to Reproduce</b>

1. Open phet.io studio wrapper
2. Go to vector screen
3. Under vector screen, model, and projectileDragCoefficientProperty set slider to 0
4. Attempt to fire projectile in sim

<b>Visuals</b>

![2019-12-06DrgCoefIOPrjctlMtn](https://user-images.githubusercontent.com/54685448/70363406-7f8d5400-1845-11ea-8dee-cafacbf58af1.gif)

**Comment by loganbraywork** [comment]
Also occurs if object diameter set to 0 under the same screen

**Comment by zepumph** [comment]
This should be fixed as part of https://github.com/phetsims/projectile-motion/issues/217. The issue was just that that slider had no business being able to go down to 0. In the range the lower bound of the range is .04, so I just made just that that numberProperty had the appropriate range. Good bug thanks!

Please confirm fixed on master and close if all is good.

**Comment by zepumph** [comment]
I also added ranges for mass and diameter so hopefully these sliders won't cause any more bugs.

**Comment by zepumph** [comment]
This needed a bit more reworking over in #217, but it should be good now. 

Please confirm fixed on master and close if all is good.

**Comment by zepumph** [comment]
@loganbraywork anything else here?

**Comment by zepumph** [comment]
@loganbraywork I'm going to close this, please reopen if there is anything more.
