### ISSUE TITLE
Add ability to independently disable cannon height and angle adjustments

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#248]
For #244

Related issues
https://github.com/phetsims/scenery/issues/1041
https://github.com/phetsims/scenery/issues/1116
https://github.com/phetsims/bending-light/issues/397

The cannon can be adjusted in two ways:

* dragging the barrel to change the angle
* dragging the cannon base/pedestal to change the height

Clients should be able to independently disable these interactions (whether by pickableProperty or its successor).

**Comment by zepumph** [comment]
I actually though it was easier to instrument on the listeners themselves, since for the height one the listener was added to many Nodes. Having the flexibility to disable based on the Node and/or listener is really nice.

Please experiment with PhET-iO elements like these, and let me know what you think:

height: `projectileMotion.introScreen.view.cannonNode.heightDragListener.enabledProperty`

rotation: `projectileMotion.introScreen.view.cannonNode.barrelTopDragListener.enabledProperty`

**Comment by zepumph** [comment]
I also fixed the cursor, so that it can come from the input listener instead of each Node that the single listener is added to. This further simplifies the file. Now, disabled input listeners will show the default cursor.

**Comment by arouinfar** [comment]
The behavior is looking really nice. One (hopefully) minor request -- when `cannonNode.heightDragListener.enabledProperty` is false can the cueing arrows be hidden?
![image](https://user-images.githubusercontent.com/8419308/127455229-a03df55f-bdf9-4702-b52b-d4613b3ae108.png)

**Comment by zepumph** [comment]
It has been done.

**Comment by arouinfar** [comment]
Looks good, thanks!
