### ISSUE TITLE
Clicking NumberDisplay should not summon keypad if corresponding edit button is hidden

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-motion#253]
For #244 

The five controls under `projectileMotion.labScreen.view.projectileControlPanel.customControl` all have a NumberDisplay + edit button. Clicking either of these will summon the keypad. 

When `editButton.visibleProperty` is false, it should not be possible to summon the keypad. However, the NumberDisplay remains pickable which is problematic.

**Comment by zepumph** [comment]
I created a new Property called `editEnabledProperty`, and it controls the enabled and the button and the numberDisplay's input listener. The editButton.enabledProperty is now a linked element. Note that NumberDisplay doesn't have this same behavior because by default (in their common code) they don't support input.

Please review.

**Comment by arouinfar** [comment]
> I created a new Property called `editEnabledProperty`

This is really nice. The behavior looks good in master, thanks!
