### ISSUE TITLE
Double checking the responsible dev listing for projectile-motion

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-motion#267]
From https://github.com/phetsims/projectile-motion/issues/266, I had a recollection that @zepumph was working on this sim, but @jbphet is listed as responsible dev.  Sorry if I'm misremembering something, but I thought I should double check just in case.  Assigning both parties and the listed responsible designer.

**Comment by jbphet** [comment]
I have historically been the responsible dev, since I worked with @andrealin quite a bit during the earlier portions of the implementation process.  @pixelzoom got heavily involved toward the end, so the logical choice was either him or me, and he had more sims, so I got it (or something like that).  @zepumph has been working to instrument the sim for phet-io, and has taken on some other open issues at the same time, so he has likely been doing more work in the repo than anyone else.

Anything else you need to know?

**Comment by samreid** [comment]
That is very helpful, thanks!  Closing.
