### ISSUE TITLE
iPad2 performance is currently sluggish 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#49]
I took a look at http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.2/projectile-motion_en.html

On Windows desktop chrome the sim appears to be performing quite smoothly, however it is a bit sluggish on iPad2. To my eye, it appears to be an issue with drawing the path of the object as it flies through the air.

@jonathanolson said he would be willing to take a look. Please spend 1-2 hours investigating. If it is something simple, and can be optimized easily, please go ahead and just make the fix, and provide an explanation for @andrea-phet.

If the investigation suggests that a significant amount of time will be needed (greater than 2 hours after the initial investigation), please reassign to me with some suggestions/estimates.

**Comment by jonathanolson** [comment]
I have a few further recommendations for performance that I'd recommend I not do on my own. I'll be happy to collaborate
or advise on any complicated parts.

(There are still some performance enhancements I'll plan to do myself, leaving assigned to me a also).

## Timesteps

Right now, it looks like 2 out of every 3 animation frames are skipped. Since the frames DT are being capped at 0.048
(48ms), anything under 20fps will start to slow down the speed of the projectile. Usually there should be a good reason
for needing to limit the DT to anything lower than 0.5s (and I don't see one in this case). With the changes described
below, I think the normal capping behavior should work, and the model should be stepped every frame. This should also
prevent certain types of choppyness or jerkiness that happens when it animates a bit more/less per frame than expected.

I would imagine ProjectileMotionModel's step function would be:
```js
/**
 * Steps the model forward in time.
 * @public
 *
 * @param {number} dt
 */
step: function( dt ) {
  dt = Math.min( 0.5, dt ); // cap DT

  if ( this.isPlayingProperty.value ) {
    for ( var i = 0; i < this.trajectories.length; i++ ) {
      this.trajectories.get( i ).step( dt );
    }
  }
}
```
and that a separate stepModelElements would not be needed.

For cases where a discrete and fixed timestep is needed, EventTimer should be used. It already handles breaking up
time into discrete chunks, and telling you exactly how far you are in-between chunks.

There's a decent chance that allowing the slight variation of DT adjusting the discrete steps here might cause problems
with friction - shooting a projectile with slightly different DTs may result in it landing in a slightly different place.
A workaround would be to use EventTimer to handle the timesteps, and then interpolate between them for current display.

## Random tips

- Generally use full-form JSDoc style comments on methods (see the step method above as an example)
- Property subtypes (NumberProperty, BooleanProperty) are generally preferred for things that are only numbers or booleans.
- Combining x/y values into a Vector2 is generally preferred, even if garbage collection should be avoided. Vector2 supports mutable operations, and can be pooled (`Vector2.createFromPool( ... )` instead of `new Vector2( ... )` or `Vector2.dirtyFromPool()` for an arbitrary state Vector2, and `vector.freeToPool()` afterwards to return it to the pool). DataPoint is harder to reason about (and math is extra verbose) currently. For instance:
```js
model.launchVelocityProperty.get() * Math.cos( model.cannonAngleProperty.get() * Math.PI / 180 ), // x velocity
model.launchVelocityProperty.get() * Math.sin( model.cannonAngleProperty.get() * Math.PI / 180 ), // y velocity
```
becomes:
```
Vector2.dirtyFromPool().setPolar( model.launchVelocityProperty.value, model.cannonAngleProperty.value * Math.PI / 180 )
```
- Using mutable operations can also help with performance - I'll plan to optimize any inner loops that are a bottleneck.

**Comment by andrea-phet** [comment]
Thanks for the recommendations. This makes sense so far, and I'll let you know if I have any questions.

**Comment by jonathanolson** [comment]
Current status on Lave (iPad 2):

- Normal animation is ~30fps
- Animation with force diagram/arrows can get down to ~20fps
- Animation when anything sticks out above the top of the sim is ~10fps
- There's still a moderate delay when pressing the "fire" button, since it creates the TrajectoryNode (and then the SVG to render that).

There may be workarounds for the "sticks out above the top" issue, but I'm curious if this happens on newer iPads (@phet-steele, is this the case?)

The delay when firing a projectile can definitely be minimized (hopefully mostly eliminated), but would require moderate changes (initially creating enough TrajectoryNodes that are invisible, then unhiding and mutating one when a projectile is fired). Long-term logic would be somewhat more complicated.

@ariel-phet, can you try a built version (let me know if a dev version should be published) to see whether further improvements are warranted?

**Comment by ariel-phet** [comment]
@jonathanolson yes, please publish a dev version

**Comment by jonathanolson** [comment]
http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.3/projectile-motion_en.html

**Comment by andrea-phet** [comment]
I noticed that there was some interesting path behavior when a new TrajectoryNode is created if an old TrajectoryNode's path is still being drawn:
![image](https://user-images.githubusercontent.com/7988696/27772690-7698d7ca-5f24-11e7-9ee1-da4869cbfcb1.png)

So in https://github.com/phetsims/projectile-motion/commit/f4d827ede028e192f6db73a523000025907d80fa I moved the declaration of the scratch vectors into the constructor, which seemed to fix the problem.

I didn't mess anything up performance wise or otherwise, did I? Assigning @jonathanolson to review.

**Comment by jonathanolson** [comment]
Looks like a good fix, thanks!

**Comment by andrea-phet** [comment]
The JSDoc is more taken care of in #57, @jonathanolson could you review the uses of NumberProperty, BooleanProperty, and Vector2 pools?

Also, could you explain what you meant in this TODO in line 194 of ProjectileNode: `//TODO: Getting a view-coordinate copy of the DataPoint would be ideal, so this extra thing wouldn't be needed.`

I am trying to dispose the listeners, and this might be related?

**Comment by andrea-phet** [comment]
I talked with @ariel-phet and @jonathanolson about performance, and it seems that the only remaining issue is that the projectile flies choppily when there are visible vectors that go off the screen (thus why it is slower on the ascent, with the velocity vector point up and out of the screen).

Assigning to @jonathanolson to take a look at.

**Comment by phet-steele** [comment]
> There may be workarounds for the "sticks out above the top" issue, but I'm curious if this happens on newer iPads (@phet-steele, is this the case?)

@jonathanolson I don't think so. Occasionally there is a dip from 60fps down to 30fps when vectors go off the top, but this is rare and probably unrelated. Generally the sim does not behave differently whether vectors are off screen, on screen, or disabled. (iPad Air 2, iOS 10.3.2)

**Comment by jonathanolson** [comment]
Current working theory is that iOS Safari watches the top row of pixels for changes so that it can change the browser "chrome" appearance to match. It at least seems to "darken" a row of pixels.

**Comment by jonathanolson** [comment]
I've somewhat narrowed down how to improve performance here, and will continue working on it tomorrow.

**Comment by jonathanolson** [comment]
@samreid's suggestion for a SVG-side clipping region (instead of a div CSS clip) looks like it may be our best solution. Many thanks!

It seems to mostly be a win for performance (most notably when the arrow goes off the screen). I'll be creating a Scenery issue to investigate if this should always be applied on mobile Safari, or if there is also a related performance degradation.

Commit above applies it to the sim for now. I'll remove it once I have a more general solution.

**Comment by pixelzoom** [comment]
@andrea-phet @jonathanolson Is there anything related to this issue that needs to be done for 1.0.0 release, or can this issue be labeled as "deferred"?

**Comment by andrea-phet** [comment]
I think deferred. Right, @jonathanolson?

**Comment by jonathanolson** [comment]
Added deferred tag for the workaround, so that we can potentially (in the future) look into a better solution.

**Comment by jbphet** [comment]
@jonathanolson and @ariel-phet - I'm going through issues in this repo due to some work that is being done for phet-io, see https://github.com/phetsims/projectile-motion/issues/178.  Can this issue be closed, or should it be left open and deferred?

**Comment by ariel-phet** [comment]
Considering we no longer support iPad2, this issue can be closed
