### ISSUE TITLE
Reduce size of buick image

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#77]
@arouinfar since we have a bit of artistic license with the displayed size of objects, I think I would reduce the size the buick a bit. In dev.5 it is pretty big, and I think it could easily be 25% smaller and work nicely.

**Comment by arouinfar** [comment]
@ariel-phet agreed. There are several scaling issues that I think are related image size and/or Hollywooding. I'm still reviewing dev.5, but will open a new issue this afternoon.

**Comment by arouinfar** [comment]
For example, a 1 m diameter golfball, baseball, and cannonball have very noticeably different sizes.
![image](https://user-images.githubusercontent.com/8419308/28030780-5cdbfcce-6562-11e7-9eab-60e5e4c8bd65.png)

**Comment by arouinfar** [comment]
@ariel-phet I reduced the Buick has been reduced by ~20%. I didn't reduce it quite as much as you suggested, so that the length would be roughly correct (now 5m, but in reality is ~5.5 m). This looks about right to me.

![image](https://user-images.githubusercontent.com/8419308/28137741-83d5574e-670b-11e7-91ba-7e2dd714eb0b.png)

**Comment by ariel-phet** [comment]
@arouinfar the new size you are showing looks good

**Comment by arouinfar** [comment]
Thanks @ariel-phet. I've sent the updated asset to @andrea-phet to implement with the changes in #81. Closing.
