### ISSUE TITLE
PhET girl a Center of Mass not quite lining up with trajectory

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#78]
@arouinfar and @andrea-phet I noticed this issue in dev.5

PhET girl seems to be a little off the trajectory, I think she sholuld be centered somewhere near her belt buckle. 

Most clear to see her offset at the apex

![capture](https://user-images.githubusercontent.com/4051174/28030642-d237e830-6561-11e7-9f4f-d5248748e6c1.PNG)

**Comment by arouinfar** [comment]
@ariel-phet I believe @andrea-phet is centering the path on the projectile's image, which sometimes is a bit off from the COM (see below), or ends up looking a little odd (like PhET girl). 

![image](https://user-images.githubusercontent.com/8419308/28030863-acfebf70-6562-11e7-8bb2-b9dd39ebeda2.png)

For the images, I can create some transparent padding so the center of the image falls on a more logical location, but I'd like to wait until #74 is implemented so I can more clearly see which images should be adjusted.

**Comment by arouinfar** [comment]
After reviewing #74, I think PhET girl and the piano are the only benchmarks that would benefit from a little extra padding. @andrea-phet has mentioned the possibility of programmatically moving the center on the Drag screen projectiles.

**Comment by arouinfar** [comment]
Flying PhET girl has been adjusted so that the center of the image falls close to the belt buckle
![image](https://user-images.githubusercontent.com/8419308/28137455-923f0fec-670a-11e7-81bd-699bdfb90203.png)

The piano has be similarly adjusted so that the center is a little higher up
![image](https://user-images.githubusercontent.com/8419308/28137499-bc84d200-670a-11e7-9019-d3d5a34ba06c.png)

I will be delivering these updated assets as a part of #81, but tagging this issue for design meeting to discuss the shifted COM for the drag object.

**Comment by arouinfar** [comment]
Tracking the COM of the drag objects in #91, so this issue can be closed.
