### ISSUE TITLE
Keep the sim paused after firing a projectile

### ISSUE THREAD

**Issue by phet-steele** [phetsims/projectile-motion#84]
@arouinfar @andrea-phet, I'm not sure I agree with the current play/pause behaviour. As is, pressing the Fire button will un-pause the sim. This prevents a user from being able to slowly step through the entire lifetime of a projectile's trajectory. This seems oddly restrictive and renders a fair amount of experiments impossible. I see no excuse for preventing the initial moments from being paused. I propose we keep the sim paused after firing.

For comparison, Neuron is nearly identical to projectile-motion in the sense of it having a "fire" button. The sim does not resume upon stimulating the neuron so that users can step through the stimulus in its entirety.

For phetsims/QA/issues/20.

**Comment by arouinfar** [comment]
Thanks @phet-steele. I think it would be valuable to allow users to step through any part of the path (including the early bits), so I agree that unpausing on fire is not ideal. Tagging for further discussion at design meeting.

**Comment by arouinfar** [comment]
Discussed during today's design meeting. @andrea-phet updated the behavior so that pressing fire will not unpause the sim. When fire is pressed, the projectile appears at the origin
![image](https://user-images.githubusercontent.com/8419308/28193640-7fc07292-67fb-11e7-8036-6900c6a3e18b.png)

Up to three projectiles can be queued up. For example, the cannonball, tank shell, and football:
![image](https://user-images.githubusercontent.com/8419308/28193658-a2d3cfea-67fb-11e7-8bb2-1bd521af1330.png)

The design team reviewed the behavior during design meeting and liked it, and this has now been implemented in dev7. 

Reassigning to @phet-steele to review and close if everything looks good.

**Comment by phet-steele** [comment]
Great, thanks all!
